spring.application.name=docflow-hub
spring.data.mongodb.uri=${MONGODB_URL}
spring.data.mongodb.database=${MONGODB_DB_NAME}
server.port=${SERVER_PORT}
 
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=${SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${SMTP_REQUIRED}
